#!/usr/bin/env node
// Narration export (Phase 10): every line the app narrates, for review and for recording.
//   node tools/narration-export.js           writes docs/narration.md (a readable script) and tools/narration.json
//   node tools/narration-export.js --check   exits 1 if either file is out of date (does not write)
// The lines come from the lesson files (via tests/load-app.js) and the movie's own cards (js/movie.js):
// NumSys.movie.helpers.narrationLines(). Each line's id is <lesson>.<scene>.<step>, which is also the name of its
// recorded audio file (assets/audio/<id>.mp3) — see tools/generate-audio.sh and tools/build-audio-manifest.js.
'use strict';

const fs = require('fs');
const path = require('path');
const { loadApp, ROOT } = require('../tests/load-app');

const MD_PATH = path.join(ROOT, 'docs', 'narration.md');
const JSON_PATH = path.join(ROOT, 'tools', 'narration.json');
const KBPS = 48;            // the audio size budget assumes mono mp3 at 48 kbps (tools/generate-audio.sh)
const BUDGET_MB = 10;

function collect(NumSys) {
  const N = NumSys || loadApp().NumSys;
  return N.movie.helpers.narrationLines().map((l) => Object.assign({ hash: N.narrator.hashText(l.text) }, l));
}

function totals(NumSys, lines) {
  const ms = lines.reduce((sum, l) => sum + NumSys.narrator.estimateMs(l.text, 1) / (NumSys.narrator.config.timeScale || 1), 0);
  const words = lines.reduce((sum, l) => sum + l.text.trim().split(/\s+/).length, 0);
  return { lines: lines.length, words, minutes: ms / 60000, mb: (ms / 1000) * KBPS / 8 / 1024 };
}

function toJson(lines) {
  return JSON.stringify(lines.map((l) => ({
    id: l.id, text: l.text, hash: l.hash, lesson: l.lessonId, scene: l.sceneId, step: l.step,
    interactive: l.interactive, movie: l.movie
  })), null, 2) + '\n';
}

function toMarkdown(NumSys, lines) {
  const t = totals(NumSys, lines);
  const lessonLines = lines.filter((l) => !l.movie);
  const movieLines = lines.filter((l) => l.movie);
  const out = [];
  out.push('# Narration script', '');
  out.push('Generated by `node tools/narration-export.js` from the lesson files. **Do not edit this file**: change the `say`',
    'text in `js/lessons/*.js` (or the movie cards in `js/movie.js`), then run the tool again.', '');
  out.push(`- ${t.lines} lines, ${t.words} words, about ${Math.round(t.minutes)} minutes at normal speed.`);
  out.push(`- Recorded as mono mp3 at ${KBPS} kbps that is about ${t.mb.toFixed(1)} MB (size budget: under ${BUDGET_MB} MB).`);
  out.push('- Each line has an id `<lesson>.<scene>.<step>`. Its recording is `assets/audio/<id>.mp3` (see `docs/recording-your-voice.md`).');
  out.push('- Lines in a "You try it!" part (marked *interactive*) are spoken in the lesson but skipped in Movie mode.');
  out.push('- Live lines (praise, quiz questions, numbers the child makes) are made up on the spot and always use the browser voice.', '');

  let lessonId = null;
  let sceneId = null;
  let lessonNo = 0;
  let sceneNo = 0;
  lessonLines.forEach((l) => {
    if ((l.lessonId !== lessonId || l.sceneId !== sceneId) && out[out.length - 1] !== '') out.push('');
    if (l.lessonId !== lessonId) {
      lessonId = l.lessonId;
      sceneId = null;
      sceneNo = 0;
      lessonNo++;
      out.push(`## ${lessonNo}. ${l.lessonTitle} (\`${l.lessonId}\`)`, '');
    }
    if (l.sceneId !== sceneId) {
      sceneId = l.sceneId;
      sceneNo++;
      out.push(`### ${lessonNo}.${sceneNo} ${l.sceneTitle || l.sceneId} (\`${l.sceneId}\`)${l.interactive ? ' *interactive*' : ''}`, '');
    }
    out.push(`${l.step + 1}. \`${l.id}\`: ${l.text}`);
  });
  out.push('');

  out.push('## Movie mode cards', '');
  out.push('Movie mode (`#/movie`) adds an opening card, a chapter card before each lesson, a "Try this later" card in place of',
    'each interactive part, and a closing card.', '');
  movieLines.forEach((l) => {
    out.push(`- \`${l.id}\`: ${l.text}`);
  });
  out.push('');
  return out.join('\n');
}

function main() {
  const { NumSys } = loadApp();
  const lines = collect(NumSys);
  const md = toMarkdown(NumSys, lines);
  const json = toJson(lines);
  if (process.argv.includes('--check')) {
    const stale = [[MD_PATH, md], [JSON_PATH, json]].filter(([p, text]) => !fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== text);
    if (stale.length) {
      console.error('narration-export: out of date: ' + stale.map(([p]) => path.relative(ROOT, p)).join(', ') +
        '. Run `node tools/narration-export.js`.');
      process.exit(1);
    }
    console.log(`narration-export: up to date (${lines.length} lines)`);
    return;
  }
  fs.writeFileSync(MD_PATH, md);
  fs.writeFileSync(JSON_PATH, json);
  const t = totals(NumSys, lines);
  console.log(`narration-export: ${t.lines} lines, ${t.words} words, ~${Math.round(t.minutes)} min ` +
    `(~${t.mb.toFixed(1)} MB as ${KBPS} kbps mp3) -> docs/narration.md, tools/narration.json`);
}

module.exports = { collect, totals, toJson, toMarkdown, KBPS, BUDGET_MB };

if (require.main === module) main();
